# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "9976e9765085ed7ecb4561fd266a92aa"
name = "discount-app"
handle = "discount-app-658"
application_url = "https://string-wiley-giants-confidential.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-4e21dcd1.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_product_listings,read_products,write_discounts,write_products"

[auth]
redirect_urls = [
  "https://string-wiley-giants-confidential.trycloudflare.com/auth/callback",
  "https://string-wiley-giants-confidential.trycloudflare.com/auth/shopify/callback",
  "https://string-wiley-giants-confidential.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
