version: '3.4'
services:
  pfbackend:
    image: backend
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    depends_on:
      - mongo_db
  mongo_db:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: test
      MONGO_INITDB_ROOT_PASSWORD: test